repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.7
    hooks:
    -   id: clang-format
        files: '^Source/.*\.(cpp|h)$'
        exclude: '^Source/(Main\.cpp|DocumentControllerSpecialisation\.h)$|^documentation/.*$'
        types_or: [c++, c, cuda]
